version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: microcommerce
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:7.4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:5050"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  mongodb:
    image: mongo:6-jammy
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin123
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin123@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    depends_on:
      - mongodb

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      REDIS_HOSTS: redis
      HTTP_USER: admin
      HTTP_PASSWORD: admin123
    ports:
      - "8082:8081"
    depends_on:
      - redis

  user-service:
    build: 
      context: .
      dockerfile: user-service/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - notification-service
    environment:
      DATABASE_URL: postgresql://admin:admin123@postgres:5432/microcommerce
      NOTIFICATION_SERVICE_URL: http://notification-service:8004

  product-service:
    build:
      context: .
      dockerfile: product-service/Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - mongodb
    environment:
      MONGODB_URL: mongodb://admin:admin123@mongodb:27017/

  order-service:
    build:
      context: .
      dockerfile: order-service/Dockerfile
    ports:
      - "8002:8002"
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgresql://admin:admin123@postgres:5432/microcommerce
      REDIS_URL: redis://redis:6379

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    ports:
      - "8003:8003"
    depends_on:
      - user-service
      - product-service
      - order-service
    environment:
      USER_SERVICE_URL: http://user-service:8000
      PRODUCT_SERVICE_URL: http://product-service:8001
      ORDER_SERVICE_URL: http://order-service:8002

  notification-service:
    build:
      context: .
      dockerfile: notification-service/Dockerfile
    ports:
      - "8004:8004"
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379

volumes:
  postgres_data:
  mongo_data:
  redis_data:
  pgadmin_data:
