version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: microcommerce
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:6-jammy
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  user-service:
    build: ./user-service
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://admin:admin123@postgres:5432/microcommerce

  product-service:
    build: ./product-service
    ports:
      - "8001:8001"
    depends_on:
      - mongodb
    environment:
      MONGODB_URL: mongodb://admin:admin123@mongodb:27017/

  order-service:
    build: ./order-service
    ports:
      - "8002:8002"
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgresql://admin:admin123@postgres:5432/microcommerce
      REDIS_URL: redis://redis:6379

  api-gateway:
    build: ./api-gateway
    ports:
      - "8003:8003"
    depends_on:
      - user-service
      - product-service
      - order-service
    environment:
      USER_SERVICE_URL: http://user-service:8000
      PRODUCT_SERVICE_URL: http://product-service:8001
      ORDER_SERVICE_URL: http://order-service:8002

  notification-service:
    build: ./notification-service
    ports:
      - "8004:8004"
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379

volumes:
  postgres_data:
  mongo_data:
  redis_data:
